<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OutfitInfoTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('outfit_info')->insert([
        
        [
            //common type warrior weapon info
            'id'=> '1',
            'p_attack'=> '4',
            'm_attack'=> '1',
            'p_def'=> '1',
            'm_def'=> '1',
            'str'=> '2',
            'int'=> '1',
            'agi'=> '3',
            'crit'=> '1',
            'crit_dmg'=> '1',
            'price'=> '20',
        ],[
            'id'=> '2',
            'p_attack'=> '4',
            'm_attack'=> '1',
            'p_def'=> '1',
            'm_def'=> '1',
            'str'=> '2',
            'int'=> '1',
            'agi'=> '3',
            'crit'=> '1',
            'crit_dmg'=> '1',
            'price'=> '20',
        ],[
            'id'=> '3',
            'p_attack'=> '4',
            'm_attack'=> '1',
            'p_def'=> '1',
            'm_def'=> '1',
            'str'=> '3',
            'int'=> '1',
            'agi'=> '1',
            'crit'=> '2',
            'crit_dmg'=> '1',
            'price'=> '20',  //done
        ],[
            //uncommon type weapon warrior info
            'id'=> '4',
            'p_attack'=> '7',
            'm_attack'=> '1',
            'p_def'=> '1',
            'm_def'=> '1',
            'str'=> '5',
            'int'=> '1',
            'agi'=> '2',
            'crit'=> '3',
            'crit_dmg'=> '2',
            'price'=> '50',
        ],[
            'id'=> '5',
            'p_attack'=> '7',
            'm_attack'=> '1',
            'p_def'=> '1',
            'm_def'=> '1',
            'str'=> '3',
            'int'=> '1',
            'agi'=> '2',
            'crit'=> '5',
            'crit_dmg'=> '2',
            'price'=> '50', //done
        ],[
            //rare type weapon warrior info
            'id'=> '6',
            'p_attack'=> '10',
            'm_attack'=> '1',
            'p_def'=> '1',
            'm_def'=> '1',
            'str'=> '4',
            'int'=> '2',
            'agi'=> '7',
            'crit'=> '5',
            'crit_dmg'=> '3',
            'price'=> '100',
        ],[
            'id'=> '7',
            'p_attack'=> '10',
            'm_attack'=> '1',
            'p_def'=> '1',
            'm_def'=> '1',
            'str'=> '4',
            'int'=> '2',
            'agi'=> '5',
            'crit'=> '7',
            'crit_dmg'=> '3',
            'price'=> '100', //done
        ],[
            //COMMON MARKSMAN WEAP INFO
            'id'=> '8',
            'p_attack'=> '4',
            'm_attack'=> '1',
            'p_def'=> '1',
            'm_def'=> '1',
            'str'=> '2',
            'int'=> '2',
            'agi'=> '3',
            'crit'=> '1',
            'crit_dmg'=> '1',
            'price'=> '20',
        ],[
            'id'=> '9',
            'p_attack'=> '4',
            'm_attack'=> '1',
            'p_def'=> '1',
            'm_def'=> '1',
            'str'=> '1',
            'int'=> '2',
            'agi'=> '2',
            'crit'=> '3',
            'crit_dmg'=> '1',
            'price'=> '20',
        ],[
            'id'=> '10',
            'p_attack'=> '4',
            'm_attack'=> '1',
            'p_def'=> '1',
            'm_def'=> '1',
            'str'=> '3',
            'int'=> '2',
            'agi'=> '1',
            'crit'=> '2',
            'crit_dmg'=> '1',
            'price'=> '20',
        ],[
            //UNCOMMON MARKSMAN WEAP
            'id'=> '11',
            'p_attack'=> '7',
            'm_attack'=> '1',
            'p_def'=> '1',
            'm_def'=> '1',
            'str'=> '5',
            'int'=> '2',
            'agi'=> '2',
            'crit'=> '3',
            'crit_dmg'=> '2',
            'price'=> '50',
        ],[
            'id'=> '12',
            'p_attack'=> '7',
            'm_attack'=> '1',
            'p_def'=> '1',
            'm_def'=> '1',
            'str'=> '3',
            'int'=> '2',
            'agi'=> '2',
            'crit'=> '5',
            'crit_dmg'=> '2',
            'price'=> '50',
        ],[
            'id'=> '13',
            'p_attack'=> '7',
            'm_attack'=> '1',
            'p_def'=> '1',
            'm_def'=> '1',
            'str'=> '2',
            'int'=> '2',
            'agi'=> '5',
            'crit'=> '3',
            'crit_dmg'=> '2',
            'price'=> '50',
        ],[
            //RARE MARKSMAN WEAP
            'id'=> '14',
            'p_attack'=> '7',
            'm_attack'=> '1',
            'p_def'=> '1',
            'm_def'=> '1',
            'str'=> '4',
            'int'=> '3',
            'agi'=> '5',
            'crit'=> '7',
            'crit_dmg'=> '3',
            'price'=> '100',
        ],[
            //COMMON MAGE WEAP
            'id'=> '15',
            'p_attack'=> '1',
            'm_attack'=> '4',
            'p_def'=> '1',
            'm_def'=> '1',
            'str'=> '1',
            'int'=> '3',
            'agi'=> '3',
            'crit'=> '2',
            'crit_dmg'=> '1',
            'price'=> '20',
        ],[
            //UNCOMMON MAGE WEAP
            'id'=> '16',
            'p_attack'=> '1',
            'm_attack'=> '7',
            'p_def'=> '1',
            'm_def'=> '1',
            'str'=> '2',
            'int'=> '4',
            'agi'=> '3',
            'crit'=> '5',
            'crit_dmg'=> '2',
            'price'=> '50',
        ],[
            //RARE MAGE WEAP
            'id'=> '17',
            'p_attack'=> '1',
            'm_attack'=> '10',
            'p_def'=> '1',
            'm_def'=> '1',
            'str'=> '4',
            'int'=> '5',
            'agi'=> '5',
            'crit'=> '7',
            'crit_dmg'=> '3',
            'price'=> '100',
        ],[
            //COMMON WARRIOR  HEAD
            'id'=> '18',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '1',
            'm_def'=> '0',
            'str'=> '0',
            'int'=> '0',
            'agi'=> '0',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '20',
        ],[
            'id'=> '19',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '0',
            'm_def'=> '1',
            'str'=> '0',
            'int'=> '0',
            'agi'=> '0',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '20',
        ],[
            //UNCOMMON WARRIOR HEAD
            'id'=> '20',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '2',
            'm_def'=> '1',
            'str'=> '0',
            'int'=> '0',
            'agi'=> '0',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '50',
        ],[
            'id'=> '21',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '1',
            'm_def'=> '2',
            'str'=> '0',
            'int'=> '0',
            'agi'=> '0',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '50',
        ],[
            //RARE WARRIOR HEAD
            'id'=> '22',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '3',
            'm_def'=> '2',
            'str'=> '0',
            'int'=> '0',
            'agi'=> '0',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '100',
        ],[
            'id'=> '23',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '2',
            'm_def'=> '3',
            'str'=> '0',
            'int'=> '0',
            'agi'=> '0',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '100',
        ],[
            'id'=> '24',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '4',
            'm_def'=> '1',
            'str'=> '0',
            'int'=> '0',
            'agi'=> '0',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '100',
        ],[
            //COMMON WARRIOR ARMS
            'id'=> '25',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '1',
            'm_def'=> '0',
            'str'=> '0',
            'int'=> '0',
            'agi'=> '0',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '20',
        ],[
            //UNCOMMON WARRIOR ARMS
            'id'=> '26',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '2',
            'm_def'=> '1',
            'str'=> '0',
            'int'=> '0',
            'agi'=> '0',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '50',
        ],[
            'id'=> '27',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '1',
            'm_def'=> '2',
            'str'=> '0',
            'int'=> '0',
            'agi'=> '0',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '50',
        ],[
            //RARE WARRIOR ARMS
            'id'=> '28',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '3',
            'm_def'=> '2',
            'str'=> '0',
            'int'=> '0',
            'agi'=> '0',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '100',
        ],[
            'id'=> '29',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '2',
            'm_def'=> '3',
            'str'=> '0',
            'int'=> '0',
            'agi'=> '0',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '100',
        ],[
            //COMMON WARRIOR TORSO
            'id'=> '30',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '1',
            'm_def'=> '0',
            'str'=> '0',
            'int'=> '0',
            'agi'=> '0',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '20',
        ],[
            //UNCOMMON WARRIOR TORSO
            'id'=> '31',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '2',
            'm_def'=> '0',
            'str'=> '1',
            'int'=> '0',
            'agi'=> '0',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '50',
        ],[
            'id'=> '32',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '2',
            'm_def'=> '0',
            'str'=> '1',
            'int'=> '0',
            'agi'=> '0',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '50',
        ],[
            //RARE WARRIOR TORSO
            'id'=> '33',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '3',
            'm_def'=> '0',
            'str'=> '2',
            'int'=> '0',
            'agi'=> '0',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '100',
        ],[
            'id'=> '34',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '3',
            'm_def'=> '0',
            'str'=> '2',
            'int'=> '0',
            'agi'=> '0',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '100',
        ],[
            'id'=> '35',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '0',
            'm_def'=> '3',
            'str'=> '2',
            'int'=> '0',
            'agi'=> '0',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '100',
        ],[
            //COMMON WARRIOR LEGS
            'id'=> '36',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '1',
            'm_def'=> '0',
            'str'=> '0',
            'int'=> '0',
            'agi'=> '0',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '20',
        ],[
            //UNCOMMON WARRIOR LEGS
            'id'=> '37',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '2',
            'm_def'=> '0',
            'str'=> '0',
            'int'=> '0',
            'agi'=> '1',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '50',
        ],[
            'id'=> '38',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '2',
            'm_def'=> '0',
            'str'=> '0',
            'int'=> '0',
            'agi'=> '1',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '50',
        ],[
            'id'=> '39',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '0',
            'm_def'=> '2',
            'str'=> '0',
            'int'=> '0',
            'agi'=> '1',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '50',
        ],[
            //RARE WARRIOR LEGS
            'id'=> '40',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '3',
            'm_def'=> '0',
            'str'=> '0',
            'int'=> '0',
            'agi'=> '2',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '100',
        ],[
            'id'=> '41',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '3',
            'm_def'=> '0',
            'str'=> '0',
            'int'=> '2',
            'agi'=> '0',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '100',
        ],[
            //COMMON WARRIOR FOOTWEAR
            'id'=> '42',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '1',
            'm_def'=> '0',
            'str'=> '0',
            'int'=> '0',
            'agi'=> '0',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '20',
        ],[
            //UNCOMMON WARRIOR FOOTWEAR
            'id'=> '43',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '1',
            'm_def'=> '0',
            'str'=> '0',
            'int'=> '0',
            'agi'=> '2',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '50',
        ],[
            'id'=> '44',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '0',
            'm_def'=> '1',
            'str'=> '0',
            'int'=> '0',
            'agi'=> '2',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '50',
        ],[
            //RARE WARRIOR FOOTWEAR
            'id'=> '45',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '0',
            'm_def'=> '2',
            'str'=> '0',
            'int'=> '0',
            'agi'=> '3',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '100',
        ],[
            //COMMON MARKSMAN HEAD
            'id'=> '46',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '1',
            'm_def'=> '0',
            'str'=> '0',
            'int'=> '0',
            'agi'=> '0',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '20',
        ],[
            //UNCOMMON MARKSMAN HEAD
            'id'=> '47',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '2',
            'm_def'=> '1',
            'str'=> '0',
            'int'=> '0',
            'agi'=> '0',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '50',
        ],[
            'id'=> '48',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '1',
            'm_def'=> '2',
            'str'=> '0',
            'int'=> '0',
            'agi'=> '0',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '50',
        ],[
            //RARE MARKSMAN HEAD
            'id'=> '49',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '3',
            'm_def'=> '2',
            'str'=> '0',
            'int'=> '0',
            'agi'=> '0',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '100',
        ],[
            'id'=> '50',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '2',
            'm_def'=> '3',
            'str'=> '0',
            'int'=> '0',
            'agi'=> '0',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '100',
        ],[
            //COMMON MARKSMAN ARMS
            'id'=> '51',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '0',
            'm_def'=> '1',
            'str'=> '0',
            'int'=> '0',
            'agi'=> '0',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '20',
        ],[
            //UNCOMMON MARKSMAN ARMS
            'id'=> '52',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '2',
            'm_def'=> '1',
            'str'=> '0',
            'int'=> '0',
            'agi'=> '0',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '50',
        ],[
            'id'=> '53',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '1',
            'm_def'=> '2',
            'str'=> '0',
            'int'=> '0',
            'agi'=> '0',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '50',
        ],[
            //RARE MARKSMAN ARMS
            'id'=> '54',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '3',
            'm_def'=> '2',
            'str'=> '0',
            'int'=> '0',
            'agi'=> '0',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '100',
        ],[
            'id'=> '55',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '2',
            'm_def'=> '3',
            'str'=> '0',
            'int'=> '0',
            'agi'=> '0',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '100',
        ],[
            //COMMON MARKSMAN TORSO
            'id'=> '56',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '1',
            'm_def'=> '0',
            'str'=> '0',
            'int'=> '0',
            'agi'=> '0',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '20',
        ],[
            //UNCOMMON MARKSMAN TORSO
            'id'=> '57',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '2',
            'm_def'=> '0',
            'str'=> '1',
            'int'=> '0',
            'agi'=> '0',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '50',
        ],[
            'id'=> '58',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '2',
            'm_def'=> '0',
            'str'=> '1',
            'int'=> '0',
            'agi'=> '0',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '50',
        ],[
            'id'=> '59',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '0',
            'm_def'=> '2',
            'str'=> '1',
            'int'=> '0',
            'agi'=> '0',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '50',
        ],[
            //RARE MARKSMAN TORSO
            'id'=> '60',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '3',
            'm_def'=> '0',
            'str'=> '2',
            'int'=> '0',
            'agi'=> '0',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '100',
        ],[
            'id'=> '61',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '0',
            'm_def'=> '3',
            'str'=> '2',
            'int'=> '0',
            'agi'=> '0',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '100',
        ],[
            //COMMON MARKSMAN LEGS
            'id'=> '62',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '1',
            'm_def'=> '0',
            'str'=> '0',
            'int'=> '0',
            'agi'=> '0',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '20',
        ],[
            //UNCOMMON MARKSMAN LEGS
            'id'=> '63',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '2',
            'm_def'=> '0',
            'str'=> '0',
            'int'=> '0',
            'agi'=> '1',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '50',
        ],[
            'id'=> '64',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '0',
            'm_def'=> '2',
            'str'=> '0',
            'int'=> '0',
            'agi'=> '1',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '50',
        ],[
            //RARE MARKSMAN LEGS
            'id'=> '65',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '3',
            'm_def'=> '0',
            'str'=> '0',
            'int'=> '0',
            'agi'=> '2',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '100',
        ],[
            'id'=> '66',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '3',
            'm_def'=> '0',
            'str'=> '0',
            'int'=> '0',
            'agi'=> '2',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '100',
        ],[
            'id'=> '67',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '0',
            'm_def'=> '3',
            'str'=> '0',
            'int'=> '0',
            'agi'=> '2',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '100',
        ],[
            //COMMON MARKSMAN FOOTWEAR
            'id'=> '68',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '1',
            'm_def'=> '0',
            'str'=> '0',
            'int'=> '0',
            'agi'=> '0',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '20',
        ],[
            //UNCOMMON MARKSMAN FOOTWEAR
            'id'=> '69',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '1',
            'm_def'=> '0',
            'str'=> '0',
            'int'=> '0',
            'agi'=> '2',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '50',
        ],[
            'id'=> '70',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '1',
            'm_def'=> '0',
            'str'=> '0',
            'int'=> '0',
            'agi'=> '2',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '50',
        ],[
            'id'=> '71',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '0',
            'm_def'=> '1',
            'str'=> '0',
            'int'=> '0',
            'agi'=> '2',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '50',
        ],[
            //RARE MARKSMAN FOOTWEAR
            'id'=> '72',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '0',
            'm_def'=> '2',
            'str'=> '0',
            'int'=> '0',
            'agi'=> '3',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '100',
        ],[
            //COMMON MAGE HEAD
            'id'=> '73',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '1',
            'm_def'=> '0',
            'str'=> '0',
            'int'=> '0',
            'agi'=> '0',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '20',
        ],[
            //UNCOMMON MAGE HEAD
            'id'=> '74',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '2',
            'm_def'=> '1',
            'str'=> '0',
            'int'=> '0',
            'agi'=> '0',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '50',
        ],[
            'id'=> '75',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '1',
            'm_def'=> '2',
            'str'=> '0',
            'int'=> '0',
            'agi'=> '0',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '50',
        ],[
            //RARE MAGE HEAD
            'id'=> '76',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '3',
            'm_def'=> '2',
            'str'=> '0',
            'int'=> '0',
            'agi'=> '0',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '100',
        ],[
            'id'=> '77',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '2',
            'm_def'=> '3',
            'str'=> '0',
            'int'=> '0',
            'agi'=> '0',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '100',
        ],[
            'id'=> '78',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '4',
            'm_def'=> '1',
            'str'=> '0',
            'int'=> '0',
            'agi'=> '0',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '100',
        ],[
            //COMMON MAGE ARMS
            'id'=> '79',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '0',
            'm_def'=> '1',
            'str'=> '0',
            'int'=> '0',
            'agi'=> '0',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '20',
        ],[
            //UNCOMMON MAGE ARMS
            'id'=> '80',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '2',
            'm_def'=> '1',
            'str'=> '0',
            'int'=> '0',
            'agi'=> '0',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '50',
        ],[
            'id'=> '81',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '1',
            'm_def'=> '2',
            'str'=> '0',
            'int'=> '0',
            'agi'=> '0',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '50',
        ],[
            //RARE MAGE ARMS
            'id'=> '82',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '3',
            'm_def'=> '2',
            'str'=> '0',
            'int'=> '0',
            'agi'=> '0',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '100',
        ],[
            'id'=> '83',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '2',
            'm_def'=> '3',
            'str'=> '0',
            'int'=> '0',
            'agi'=> '0',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '100',
        ],[
            //COMMON MAGE TORSO
            'id'=> '84',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '1',
            'm_def'=> '0',
            'str'=> '0',
            'int'=> '0',
            'agi'=> '0',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '20',
        ],[
            //UNCOMMON MAGE TORSO
            'id'=> '85',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '2',
            'm_def'=> '0',
            'str'=> '0',
            'int'=> '0',
            'agi'=> '1',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '50',
        ],[
            'id'=> '86',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '0',
            'm_def'=> '2',
            'str'=> '0',
            'int'=> '0',
            'agi'=> '1',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '50',
        ],[
            //RARE MAGE TORSO
            'id'=> '87',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '3',
            'm_def'=> '0',
            'str'=> '0',
            'int'=> '0',
            'agi'=> '2',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '100',
        ],[
            'id'=> '88',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '0',
            'm_def'=> '3',
            'str'=> '0',
            'int'=> '0',
            'agi'=> '2',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '100',
        ],[
            //COMMON MAGE LEGS
            'id'=> '89',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '1',
            'm_def'=> '0',
            'str'=> '0',
            'int'=> '0',
            'agi'=> '0',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '20',
        ],[
            //UNCOMMON MAGE LEGS
            'id'=> '90',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '2',
            'm_def'=> '0',
            'str'=> '0',
            'int'=> '1',
            'agi'=> '0',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '50',
        ],[
            'id'=> '91',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '0',
            'm_def'=> '2',
            'str'=> '0',
            'int'=> '1',
            'agi'=> '0',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '50',
        ],[
            //RARE MAGE LEGS
            'id'=> '92',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '3',
            'm_def'=> '0',
            'str'=> '0',
            'int'=> '2',
            'agi'=> '0',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '100',
        ],[
            'id'=> '93',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '3',
            'm_def'=> '0',
            'str'=> '0',
            'int'=> '2',
            'agi'=> '0',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '100',
        ],[
            'id'=> '94',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '0',
            'm_def'=> '3',
            'str'=> '0',
            'int'=> '2',
            'agi'=> '0',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '100',
        ],[
            //COMMON MAGE FOOTWEAR
            'id'=> '95',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '1',
            'm_def'=> '0',
            'str'=> '0',
            'int'=> '0',
            'agi'=> '0',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '20',
        ],[
            //UNCOMMON MAGE FOOTWEAR
            'id'=> '96',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '1',
            'm_def'=> '0',
            'str'=> '0',
            'int'=> '2',
            'agi'=> '0',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '50',
        ],[
            'id'=> '97',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '1',
            'm_def'=> '0',
            'str'=> '0',
            'int'=> '2',
            'agi'=> '0',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '50',
        ],[
            'id'=> '98',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '0',
            'm_def'=> '1',
            'str'=> '0',
            'int'=> '2',
            'agi'=> '0',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '50',
        ],[
            //RARE MAGE FOOTWEAR
            'id'=> '99',
            'p_attack'=> '0',
            'm_attack'=> '0',
            'p_def'=> '0',
            'm_def'=> '2',
            'str'=> '0',
            'int'=> '3',
            'agi'=> '0',
            'crit'=> '0',
            'crit_dmg'=> '0',
            'price'=> '100',
        ]
    ]);
    }
}
