<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OutfitInfoTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('outfit_info')->insert([
        
        [
            //common type warrior weapon info
            'id'=> '1',
            'p_attack'=> '1',
            'm_attack'=> '1',
            'p_def'=> '1',
            'm_def'=> '1',
            'str'=> '1',
            'int'=> '1',
            'agi'=> '1',
            'crit'=> '1',
            'crit_dmg'=> '1',
            'price'=> '1',
        ],[
            'id'=> '2',
            'p_attack'=> '1',
            'm_attack'=> '1',
            'p_def'=> '1',
            'm_def'=> '1',
            'str'=> '1',
            'int'=> '1',
            'agi'=> '1',
            'crit'=> '1',
            'crit_dmg'=> '1',
            'price'=> '1',
        ],[
            'id'=> '3',
            'p_attack'=> '1',
            'm_attack'=> '1',
            'p_def'=> '1',
            'm_def'=> '1',
            'str'=> '1',
            'int'=> '1',
            'agi'=> '1',
            'crit'=> '1',
            'crit_dmg'=> '1',
            'price'=> '1',
        ],[
            'id'=> '4',
            'p_attack'=> '1',
            'm_attack'=> '1',
            'p_def'=> '1',
            'm_def'=> '1',
            'str'=> '1',
            'int'=> '1',
            'agi'=> '1',
            'crit'=> '1',
            'crit_dmg'=> '1',
            'price'=> '1',
        ],[
            'id'=> '5',
            'p_attack'=> '1',
            'm_attack'=> '1',
            'p_def'=> '1',
            'm_def'=> '1',
            'str'=> '1',
            'int'=> '1',
            'agi'=> '1',
            'crit'=> '1',
            'crit_dmg'=> '1',
            'price'=> '1',
        ],[
            'id'=> '6',
            'p_attack'=> '1',
            'm_attack'=> '1',
            'p_def'=> '1',
            'm_def'=> '1',
            'str'=> '1',
            'int'=> '1',
            'agi'=> '1',
            'crit'=> '1',
            'crit_dmg'=> '1',
            'price'=> '1',
        ],[
            //uncommon type weapon warrior info
            'id'=> '7',
            'p_attack'=> '2',
            'm_attack'=> '2',
            'p_def'=> '2',
            'm_def'=> '2',
            'str'=> '2',
            'int'=> '2',
            'agi'=> '2',
            'crit'=> '2',
            'crit_dmg'=> '2',
            'price'=> '2',
        ],[
            
            'id'=> '8',
            'p_attack'=> '2',
            'm_attack'=> '2',
            'p_def'=> '2',
            'm_def'=> '2',
            'str'=> '2',
            'int'=> '2',
            'agi'=> '2',
            'crit'=> '2',
            'crit_dmg'=> '2',
            'price'=> '2',
        ],[
            
            'id'=> '9',
            'p_attack'=> '2',
            'm_attack'=> '2',
            'p_def'=> '2',
            'm_def'=> '2',
            'str'=> '2',
            'int'=> '2',
            'agi'=> '2',
            'crit'=> '2',
            'crit_dmg'=> '2',
            'price'=> '2',
        ],[
           
            'id'=> '10',
            'p_attack'=> '2',
            'm_attack'=> '2',
            'p_def'=> '2',
            'm_def'=> '2',
            'str'=> '2',
            'int'=> '2',
            'agi'=> '2',
            'crit'=> '2',
            'crit_dmg'=> '2',
            'price'=> '2',
        ],[
            //rare type weapon warrior info
            'id'=> '11',
            'p_attack'=> '3',
            'm_attack'=> '3',
            'p_def'=> '3',
            'm_def'=> '3',
            'str'=> '3',
            'int'=> '3',
            'agi'=> '3',
            'crit'=> '3',
            'crit_dmg'=> '3',
            'price'=> '3',
        ],[
            'id'=> '12',
            'p_attack'=> '3',
            'm_attack'=> '3',
            'p_def'=> '3',
            'm_def'=> '3',
            'str'=> '3',
            'int'=> '3',
            'agi'=> '3',
            'crit'=> '3',
            'crit_dmg'=> '3',
            'price'=> '3',
            ],[
            'id'=> '13',
            'p_attack'=> '3',
            'm_attack'=> '3',
            'p_def'=> '3',
            'm_def'=> '3',
            'str'=> '3',
            'int'=> '3',
            'agi'=> '3',
            'crit'=> '3',
            'crit_dmg'=> '3',
            'price'=> '3',
            ],[
             'id'=> '14',
            'p_attack'=> '3',
            'm_attack'=> '3',
            'p_def'=> '3',
            'm_def'=> '3',
            'str'=> '3',
            'int'=> '3',
            'agi'=> '3',
            'crit'=> '3',
            'crit_dmg'=> '3',
            'price'=> '3',  
            ],[
                //COMMON MARKSMAN WEAP INFO
            'id'=> '15',
            'p_attack'=> '1',
            'm_attack'=> '1',
            'p_def'=> '1',
            'm_def'=> '1',
            'str'=> '1',
            'int'=> '1',
            'agi'=> '1',
            'crit'=> '1',
            'crit_dmg'=> '1',
            'price'=> '1',
            ],[
            'id'=> '16',
            'p_attack'=> '1',
            'm_attack'=> '1',
            'p_def'=> '1',
            'm_def'=> '1',
            'str'=> '1',
            'int'=> '1',
            'agi'=> '1',
            'crit'=> '1',
            'crit_dmg'=> '1',
            'price'=> '1',
            ],[
            'id'=> '17',
            'p_attack'=> '1',
            'm_attack'=> '1',
            'p_def'=> '1',
            'm_def'=> '1',
            'str'=> '1',
            'int'=> '1',
            'agi'=> '1',
            'crit'=> '1',
            'crit_dmg'=> '1',
            'price'=> '1',
            ],[
            //UNCOMMON MARKSMAN WEAP
            'id'=> '18',
            'p_attack'=> '2',
            'm_attack'=> '2',
            'p_def'=> '2',
            'm_def'=> '2',
            'str'=> '2',
            'int'=> '2',
            'agi'=> '2',
            'crit'=> '2',
            'crit_dmg'=> '2',
            'price'=> '2',
            ],[
            'id'=> '19',
            'p_attack'=> '2',
            'm_attack'=> '2',
            'p_def'=> '2',
            'm_def'=> '2',
            'str'=> '2',
            'int'=> '2',
            'agi'=> '2',
            'crit'=> '2',
            'crit_dmg'=> '2',
            'price'=> '2',
            ],[
            'id'=> '20',
            'p_attack'=> '2',
            'm_attack'=> '2',
            'p_def'=> '2',
            'm_def'=> '2',
            'str'=> '2',
            'int'=> '2',
            'agi'=> '2',
            'crit'=> '2',
            'crit_dmg'=> '2',
            'price'=> '2',
            ],[
                //RARE MARKSMAN WEAP
            'id'=> '21',
            'p_attack'=> '3',
            'm_attack'=> '3',
            'p_def'=> '3',
            'm_def'=> '3',
            'str'=> '3',
            'int'=> '3',
            'agi'=> '3',
            'crit'=> '3',
            'crit_dmg'=> '3',
            'price'=> '3',
            ],[
            //COMMON MAGE WEAP
            'id'=> '22',
            'p_attack'=> '1',
            'm_attack'=> '1',
            'p_def'=> '1',
            'm_def'=> '1',
            'str'=> '1',
            'int'=> '1',
            'agi'=> '1',
            'crit'=> '1',
            'crit_dmg'=> '1',
            'price'=> '1',
            ],[
            //UNCOMMON MAGE WEAP
            'id'=> '23',
            'p_attack'=> '2',
            'm_attack'=> '2',
            'p_def'=> '2',
            'm_def'=> '2',
            'str'=> '2',
            'int'=> '2',
            'agi'=> '2',
            'crit'=> '2',
            'crit_dmg'=> '2',
            'price'=> '2',
            ],[
            //RARE MAGE WEAP
            'id'=> '24',
            'p_attack'=> '3',
            'm_attack'=> '3',
            'p_def'=> '3',
            'm_def'=> '3',
            'str'=> '3',
            'int'=> '3',
            'agi'=> '3',
            'crit'=> '3',
            'crit_dmg'=> '3',
            'price'=> '3',
            ],[
                //COMMON WARRIOR  HEAD
            'id'=> '25',
            'p_attack'=> '1',
            'm_attack'=> '1',
            'p_def'=> '1',
            'm_def'=> '1',
            'str'=> '1',
            'int'=> '1',
            'agi'=> '1',
            'crit'=> '1',
            'crit_dmg'=> '1',
            'price'=> '1',
            ],[
            'id'=> '26',
            'p_attack'=> '1',
            'm_attack'=> '1',
            'p_def'=> '1',
            'm_def'=> '1',
            'str'=> '1',
            'int'=> '1',
            'agi'=> '1',
            'crit'=> '1',
            'crit_dmg'=> '1',
            'price'=> '1',
            ]
    ]);
    }
}
